Algoritmo "operacao"

Var
area, base, altura : real

Inicio
escreval (" digite a base do triangulo ")
leia (base)

escreval (" digite a altura do triangulo ")
leia (altura)

escreval (" digite a area do triangulo ")
leia (area)

limpatela

area <- (base * altura)/2

escreval (" a base do triangulo ", base)
escreval (" a altura do triangulo ", altura)
escreval (" a  area do triangulo ", area)



Fimalgoritmo